project_reg/app_reg/urls.py
from django.urls import path
from app_reg import views

app_name = 'app_reg'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('data/', views.data, name='data'),
]

project_reg/project_reg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_reg.urls')),
]

project_reg/app_reg/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class profileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

project_reg/app_reg/forms.py
from django import forms
from django.contrib.auth.models import User
from app_reg.models import profileModel

class userForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class profileForm(forms.ModelForm):
    class Meta():
        model = profileModel
        fields = ('portfolio','profile_pic')

project_reg/app_reg/views.py
from django.shortcuts import render
from app_reg.forms import userForm, profileForm
from app_reg.models import profileModel
from django.contrib.auth.models import User

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request, 'app_reg/index.html')

def registration(request):

    registered = False
    if request.method == "POST":
        user_form = userForm(request.POST)
        profile_form = profileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = userForm()
        profile_form = profileForm()

    return render(request, 'app_reg/registration.html', {'user_form':user_form,
                                                        'profile_form':profile_form,
                                                        'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('app_reg:data'))
            else:
                return HttpResponse("Account not active")
        else:
            print(f"username: {username}, password: {password}")
            return HttpResponse("Invalid username/password")
    else:
        return render(request, 'app_reg/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('app_reg:index'))

@login_required
def data(request):
    data = User.objects.order_by('id')
    return render(request, 'app_reg/data.html', {'data':data})

project_reg/templates/app_reg/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'app_reg:index' %}">Django</a></li>

          <li><a class="navbar-link" href="{% url 'app_reg:registration' %}">Registration</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'app_reg:data' %}">Data</a></li>
            <li><a class="navbar-link" href="{% url 'app_reg:user_logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'app_reg:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

  </body>
</html>

project_reg/templates/app_reg/data.html
{% extends 'app_reg/base.html' %}
{% block content %}
<h1>All data shown here</h1>
{% if data %}
  <table>
    <th>Username</th>
    <th>Email</th>
    {% for item in data %}
      <tr>
        <td>{{item.username}}</td>
        <td>{{item.email}}</td>
      </tr>
    {% endfor %}

  </table>
{% else %}
  <h2>No data available.</h2>

{% endif %}
{% endblock %}

project_reg/templates/app_reg/index.html
{% extends 'app_reg/base.html' %}
{% block content %}
<div class="jumbotron">
  <h1>Welcome to Project Registration.</h1>
</div>
{% endblock %}

project_reg/templates/app_reg/login.html
{% extends 'app_reg/base.html' %}
{% block content %}

<div class="jumbotron">
  <h1>Login Here</h1>
  <form action="{% url 'app_reg:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">username: </label>
    <input type="text" name="username" placeholder="username here">
    <label for="password">password: </label>
    <input type="password" name="password">
    <input type="submit" name="" value="Login">
  </form>
</div>

{% endblock %}

project_reg/templates/app_reg/registration.html
{% extends 'app_reg/base.html' %}
{% block content %}
<div class="jumbotron">
  <h1>Welcome to Registration Page.</h1>
</div>
<div class="container">
  {% if registered %}
    <h1>Thank you for resitering!</h1>

  {% else %}
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <input type="submit" name="" value="Submit">
    </form>
  {% endif %}
</div>

{% endblock %}